Repository ironcore-dev/metal-load-balancer-controller, pull requests merged in 2024-09, with the labels that each got.

#6 Fix container build
  Dockerfile
Labels: bug, enhancement, size/XS, ok-to-image

#7 Update Daemonset Config
  config/metalbond-client/daemonset.yaml
Labels: bug, size/S

#8 Add predicate filter for `metalbond-speaker`
  internal/metalbond-speaker/service_controller.go
Labels: enhancement, size/XS

#14 Implement Node IPAM Controller
  PROJECT
  cmd/metal-load-balancer-controller/main.go
  config/rbac/role.yaml
  internal/metal-load-balancer-controller/node_ipam_controller.go
  internal/metal-load-balancer-controller/node_ipam_controller_test.go
  internal/metal-load-balancer-controller/suite_test.go
Labels: enhancement, size/L

#15 Add Speaker Kustomization and RBAC
  .gitignore
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
  config/manager/speaker.yaml
  config/rbac/role.yaml
  config/rbac/service_editor_role.yaml
  config/rbac/service_viewer_role.yaml
  internal/metal-load-balancer-controller/service_controller.go
  internal/metalbond-speaker/service_controller.go
Labels: bug, size/M

#16 Add Wait for the Peer Connection to be Established
  cmd/metalbond-speaker/main.go
Labels: bug, size/S

#17 Add finalizers and avoid re-announcing routes
  go.mod
  go.sum
  internal/metalbond-speaker/service_controller.go
Labels: bug, size/M

#18 Add init container for overlay-tunnel
  config/manager/speaker.yaml
Labels: enhancement, size/S
